version: "3"

services:

  postgres:
    image: docker.office.beone.pl/postgres-pl:11.1
    command: postgres -c max_connections=300
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./data/postgres/initdb:/docker-entrypoint-initdb.d
    networks:
      - postgres

  alfresco:
    image: docker.office.beone.pl/alfresco:201707-build-00028
    ports:
    - 8070:8080
    - 8075:8000
    - "8072:22"
    depends_on:
    - postgres
    environment:
    - 'JAVA_OPTS_MEMORY=-Xms1G -Xmx1G -XX:NewSize=256m -XX:MaxNewSize=256m'

    ###
    - PROP|ALFRESCO_GLOBAL|db.driver=org.postgresql.Driver
    - PROP|ALFRESCO_GLOBAL|db.url=jdbc:postgresql://postgres:5432/alfresco
    - PROP|ALFRESCO_GLOBAL|db.username=postgres
    - PROP|ALFRESCO_GLOBAL|db.password=postgres
    - PROP|ALFRESCO_GLOBAL|db.pool.validate.query=SELECT 1

    - PROP|ALFRESCO_GLOBAL|transformation.server.host=172.19.0.1
    - PROP|ALFRESCO_GLOBAL|transformation.server.port=8010

      ###
    - REMOVE_LIB|1=httpclient-4.3.3.jar
    - REMOVE_LIB|2=httpcore-4.3.2.jar
    volumes:
    - alfresco:/opt/alfresco/alf_data

    - ./data/amp/alfresco:/opt/alfresco/amps
    networks:
    - postgres
    - alfresco
    - solr4

  share:
    image: docker.office.beone.pl/share:201707-build-00028
    ports:
    - 8080:8080
    - 8085:8000
    environment:
    - 'JAVA_OPTS_MEMORY=-Xms512m -Xmx512m -XX:NewSize=128m -XX:MaxNewSize=128m'

    - REGEX|SHARE_CONFIG_CUSTOM|(http://localhost:8080/alfresco)=http://alfresco:8080

    - PROP|LOG|log4j.logger.org.alfresco.repo.jscript.ScriptLogger=DEBUG
    depends_on:
    - alfresco
    volumes:
    - ./data/amp/share:/opt/share/amps
    networks:
    - alfresco
    - share

  solr4:
    image: docker.office.beone.pl/solr4:201707-build-00028
    ports:
    - 8060:8080
    - 8065:8000
    - "8062:22"
    depends_on:
    - alfresco
    environment:
    - 'JAVA_OPTS_MEMORY=-Xms1G -Xmx1G -XX:NewSize=256m -XX:MaxNewSize=256m'

    - PROP|WORKSPACE|alfresco.host=alfresco
    - PROP|WORKSPACE|alfresco.cron=0/3 * * * * ? *
    - PROP|WORKSPACE|alfresco.baseUrl=
    - PROP|WORKSPACE|alfresco.secureComms=none
    - PROP|WORKSPACE|alfresco.corePoolSize=2

    - PROP|ARCHIVE|alfresco.host=alfresco
    - PROP|ARCHIVE|alfresco.cron=0 0/15 * * * ? *
    - PROP|ARCHIVE|alfresco.baseUrl=
    - PROP|ARCHIVE|alfresco.secureComms=none
    - PROP|ARCHIVE|alfresco.corePoolSize=1

    - PROP|LOG|log4j.logger.org.alfresco.solr.tracker.AbstractTracker=OFF
    volumes:
    - solr4:/srv/solr4
    networks:
    - alfresco
    - solr4

#  transformation-server:
#    image: docker.office.beone.pl/transformation-server:3.0.0-alpha
#    ports:
#      - 8080:8080
#      - 9999:9999
#    environment:
#      ENV_HOST: transformation-server
#      ENV_REST_HOST: transformation-server
#      ENV_SEED_NODE_1: akka.tcp://TransformationServer@transformation-server:2551
#      ENV_SEED_NODE_2: akka.tcp://TransformationServer@transformation-server2:2551
#
#      A: 1
#      B: 0
#    volumes:
#      - ./../ex/transformation-server-core/transformation-server-core-executable/target/transformation-server-core-executable-3.0.0-alpha-allinone.jar:/opt/transformation-server-executable-3.0.0-alpha-allinone.jar
#    networks:
#      - transformation-server
#      - transformation-server2
#
#  transformation-server2:
#    image: docker.office.beone.pl/transformation-server:3.0.0-alpha
#    ports:
#      - 8070:8080
#    environment:
#      ENV_HOST: transformation-server2
#      ENV_REST_HOST: transformation-server2
#      ENV_SEED_NODE_1: akka.tcp://TransformationServer@transformation-server:2551
#      ENV_SEED_NODE_2: akka.tcp://TransformationServer@transformation-server2:2551
#
#      A: 1
#      B: 1
#    volumes:
#      - ./../ex/transformation-server-core/transformation-server-core-executable/target/transformation-server-core-executable-3.0.0-alpha-allinone.jar:/opt/transformation-server-executable-3.0.0-alpha-allinone.jar
#    networks:
#      - transformation-server
#      - transformation-server2

volumes:
  postgres:
  alfresco:
  solr4:

networks:
  postgres:
  alfresco:
  share:
  solr4:
#  transformation-server:
#  transformation-server2: