package pl.beone.promena.connector.normal.http

object PromenaNormalHttpHeaders {

    val TRANSFORMATION_PREFIX_REGEX = """^transformation\d*-""".toRegex()
    const val TRANSFORMATION_TRANSFORMER_ID_NAME_SUFFIX = "transformerId-name"
    val TRANSFORMATION_TRANSFORMER_ID_NAME_REGEX = "$TRANSFORMATION_PREFIX_REGEX$TRANSFORMATION_TRANSFORMER_ID_NAME_SUFFIX".toRegex()
    const val TRANSFORMATION_TRANSFORMER_ID_SUB_NAME_SUFFIX = "transformerId-subName"
    val TRANSFORMATION_TRANSFORMER_ID_SUB_NAME_REGEX = "$TRANSFORMATION_PREFIX_REGEX$TRANSFORMATION_TRANSFORMER_ID_SUB_NAME_SUFFIX".toRegex()
    const val TRANSFORMATION_MEDIA_TYPE_MIME_TYPE_SUFFIX = "mediaType-mimeType"
    val TRANSFORMATION_MEDIA_TYPE_MIME_TYPE_REGEX = "$TRANSFORMATION_PREFIX_REGEX$TRANSFORMATION_MEDIA_TYPE_MIME_TYPE_SUFFIX".toRegex()
    const val TRANSFORMATION_MEDIA_TYPE_CHARSET_SUFFIX = "mediaType-charset"
    val TRANSFORMATION_MEDIA_TYPE_CHARSET_REGEX = "$TRANSFORMATION_PREFIX_REGEX$TRANSFORMATION_MEDIA_TYPE_CHARSET_SUFFIX".toRegex()

    const val DATA_DESCRIPTOR_PREFIX = "dataDescriptor-"
    const val DATA_DESCRIPTOR_MEDIA_TYPE_MIME_TYPE = "${DATA_DESCRIPTOR_PREFIX}mediaType-mimeType"
    const val DATA_DESCRIPTOR_MEDIA_TYPE_CHARSET = "${DATA_DESCRIPTOR_PREFIX}mediaType-charset"
}