package pl.beone.promena.transformer.applicationmodel.mediatype

object MediaTypeConstants {

    val APPLICATION_OCTET_STREAM = MediaType.create("application/octet-stream", Charsets.UTF_8)
    val APPLICATION_ECMASCRIPT = MediaType.create("application/ecmascript", Charsets.UTF_8)
    val APPLICATION_EPUB_ZIP = MediaType.create("application/epub+zip", Charsets.UTF_8)
    val APPLICATION_JAVASCRIPT = MediaType.create("application/javascript", Charsets.UTF_8)
    val APPLICATION_JAVA_ARCHIVE = MediaType.create("application/java-archive", Charsets.UTF_8)
    val APPLICATION_JSON = MediaType.create("application/json", Charsets.UTF_8)
    val APPLICATION_MSWORD = MediaType.create("application/msword", Charsets.UTF_8)
    val APPLICATION_OGG = MediaType.create("application/ogg", Charsets.UTF_8)
    val APPLICATION_PDF = MediaType.create("application/pdf", Charsets.UTF_8)
    val APPLICATION_RTF = MediaType.create("application/rtf", Charsets.UTF_8)
    val APPLICATION_TYPESCRIPT = MediaType.create("application/typescript", Charsets.UTF_8)
    val APPLICATION_VND_AMAZON_EBOOK = MediaType.create("application/vnd.amazon.ebook", Charsets.UTF_8)
    val APPLICATION_VND_APPLE_INSTALLER_XML = MediaType.create("application/vnd.apple.installer+xml", Charsets.UTF_8)
    val APPLICATION_VND_MOZILLA_XUL_XML = MediaType.create("application/vnd.mozilla.xul+xml", Charsets.UTF_8)
    val APPLICATION_VND_MS_EXCEL = MediaType.create("application/vnd.ms-excel", Charsets.UTF_8)
    val APPLICATION_VND_MS_FONTOBJECT = MediaType.create("application/vnd.ms-fontobject", Charsets.UTF_8)
    val APPLICATION_VND_MS_POWERPOINT = MediaType.create("application/vnd.ms-powerpoint", Charsets.UTF_8)
    val APPLICATION_VND_OASIS_OPENDOCUMENT_PRESENTATION = MediaType.create("application/vnd.oasis.opendocument.presentation", Charsets.UTF_8)
    val APPLICATION_VND_OASIS_OPENDOCUMENT_SPREADSHEET = MediaType.create("application/vnd.oasis.opendocument.spreadsheet", Charsets.UTF_8)
    val APPLICATION_VND_OASIS_OPENDOCUMENT_TEXT = MediaType.create("application/vnd.oasis.opendocument.text", Charsets.UTF_8)
    val APPLICATION_VND_OPENXMLFORMATS_OFFICEDOCUMENT_PRESENTATIONML_PRESENTATION =
            MediaType.create("application/vnd.openxmlformats-officedocument.presentationml.presentation", Charsets.UTF_8)
    val APPLICATION_VND_OPENXMLFORMATS_OFFICEDOCUMENT_SPREADSHEETML_SHEET =
            MediaType.create("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", Charsets.UTF_8)
    val APPLICATION_VND_OPENXMLFORMATS_OFFICEDOCUMENT_WORDPROCESSINGML_DOCUMENT =
            MediaType.create("application/vnd.openxmlformats-officedocument.wordprocessingml.document", Charsets.UTF_8)
    val APPLICATION_VND_VISIO = MediaType.create("application/vnd.visio", Charsets.UTF_8)
    val APPLICATION_XHTML_XML = MediaType.create("application/xhtml+xml", Charsets.UTF_8)
    val APPLICATION_XML = MediaType.create("application/xml", Charsets.UTF_8)
    val APPLICATION_X_7Z_COMPRESSED = MediaType.create("application/x-7z-compressed", Charsets.UTF_8)
    val APPLICATION_X_ABIWORD = MediaType.create("application/x-abiword", Charsets.UTF_8)
    val APPLICATION_X_BZIP = MediaType.create("application/x-bzip", Charsets.UTF_8)
    val APPLICATION_X_BZIP2 = MediaType.create("application/x-bzip2", Charsets.UTF_8)
    val APPLICATION_X_CSH = MediaType.create("application/x-csh", Charsets.UTF_8)
    val APPLICATION_X_RAR_COMPRESSED = MediaType.create("application/x-rar-compressed", Charsets.UTF_8)
    val APPLICATION_X_SH = MediaType.create("application/x-sh", Charsets.UTF_8)
    val APPLICATION_X_SHOCKWAVE_FLASH = MediaType.create("application/x-shockwave-flash", Charsets.UTF_8)
    val APPLICATION_X_TAR = MediaType.create("application/x-tar", Charsets.UTF_8)
    val APPLICATION_ZIP = MediaType.create("application/zip", Charsets.UTF_8)
    val AUDIO_AAC = MediaType.create("audio/aac", Charsets.UTF_8)
    val AUDIO_MIDI = MediaType.create("audio/midi", Charsets.UTF_8)
    val AUDIO_OGG = MediaType.create("audio/ogg", Charsets.UTF_8)
    val AUDIO_WAV = MediaType.create("audio/wav", Charsets.UTF_8)
    val AUDIO_WEBM = MediaType.create("audio/webm", Charsets.UTF_8)
    val FONT_OTF = MediaType.create("font/otf", Charsets.UTF_8)
    val FONT_TTF = MediaType.create("font/ttf", Charsets.UTF_8)
    val FONT_WOFF = MediaType.create("font/woff", Charsets.UTF_8)
    val FONT_WOFF2 = MediaType.create("font/woff2", Charsets.UTF_8)
    val IMAGE_GIF = MediaType.create("image/gif", Charsets.UTF_8)
    val IMAGE_JPEG = MediaType.create("image/jpeg", Charsets.UTF_8)
    val IMAGE_PNG = MediaType.create("image/png", Charsets.UTF_8)
    val IMAGE_SVG_XML = MediaType.create("image/svg+xml", Charsets.UTF_8)
    val IMAGE_TIFF = MediaType.create("image/tiff", Charsets.UTF_8)
    val IMAGE_WEBP = MediaType.create("image/webp", Charsets.UTF_8)
    val IMAGE_X_ICON = MediaType.create("image/x-icon", Charsets.UTF_8)
    val TEXT_CALENDAR = MediaType.create("text/calendar", Charsets.UTF_8)
    val TEXT_CSS = MediaType.create("text/css", Charsets.UTF_8)
    val TEXT_CSV = MediaType.create("text/csv", Charsets.UTF_8)
    val TEXT_HTML = MediaType.create("text/html", Charsets.UTF_8)
    val TEXT_PLAIN = MediaType.create("text/plain", Charsets.UTF_8)
    val TEXT_XML = MediaType.create("text/xml", Charsets.UTF_8)
    val VIDEO_3GPP = MediaType.create("video/3gpp", Charsets.UTF_8)
    val VIDEO_3GPP2 = MediaType.create("video/3gpp2", Charsets.UTF_8)
    val VIDEO_MPEG = MediaType.create("video/mpeg", Charsets.UTF_8)
    val VIDEO_OGG = MediaType.create("video/ogg", Charsets.UTF_8)
    val VIDEO_WEBM = MediaType.create("video/webm", Charsets.UTF_8)
    val VIDEO_X_MSVIDEO = MediaType.create("video/x-msvideo", Charsets.UTF_8)

}